### PR TITLE
docs(typo): package -> password

### PR DESCRIPTION
**Pull request by BlueFalconHD**
lol this is huge idk i need to get into nix but its scary

anyway found this typo :3

### CODE REVIEW

**Review by isabelroses — APPROVED** [review]
thanks for the catch

**Comment by isabelroses** [comment]
> lol this is huge idk i need to get into nix but its scary

Yeah, I wouldn't follow my config really, it's quite quirky, it has to support a lot of very different hardware unless you need that I would recommended, [winston's config](https://github.com/nekowinston/dotfiles) or [amys](https://github.com/nullishamy/derivation-station).

**Comment by BlueFalconHD** [comment]
> > lol this is huge idk i need to get into nix but its scary
> 
> Yeah, I wouldn't follow my config really, it's quite quirky, it has to support a lot of very different hardware unless you need that.
> 
> I would recommended, [winston's config](https://github.com/nekowinston/dotfiles) or [amys](https://github.com/nullishamy/derivation-station).

Nix is basically just a scripting language right?

**Comment by isabelroses** [comment]
> Nix is basically just a scripting language right?

Its a functional programming language like Haskell, which is partly why it leads to reproducible builds.

**Pull request merged**
